export const FIGMA_ID = 'XQOznCEf9YgqLGFIBou010'
export const TOKEN = 'figd_gl1u0MYJE6Pfw619EDkoNxWIzbJ0BxqH8HnRmEMC'
export const LOGIN_NODE = '1-2'
export const LOGIN_IMAGE_NAME = 'login.png'
export const PRODUCT_NODE = '108-227'
export const PRODUCT_IMAGE_NAME = 'product.png'